name: BookHead
description: Make heads from books
author: StarTux
version: 0.1
main: com.winthier.bookhead.BookHeadPlugin
depend: []
commands:
  bookhead:
    description: Turn book in hand into player head
    permission: bookhead.create
    usage: Hold a signed book with nothing but the code in your hand!
permissions:
  bookhead.create:
    description: Create a head using a book
    default: op
